### PR TITLE
check if the blueprint_type has a valid semmantic version

### LINKED ISSUE #224: Release PR failing int test
Release PR failing int test due to blueprint_type hardcoded in test. 
We will be hardcoding the output in https://github.com/GoogleCloudPlatform/terraform-google-secured-data-warehouse/pull/207 this should resolve itself but eventually we may move to dynamic updates via release-please so we should drop the explicit version check in test.

```
×  check blueprint_type blueprints/terraform/terraform-google-secured-data-warehouse/v0.1.0 should have expected value
     
     expected: "blueprints/terraform/terraform-google-secured-data-warehouse/v1.0.0"
          got: "blueprints/terraform/terraform-google-secured-data-warehouse/v0.1.0"
```

### PR DESCRIPTION
**Pull request by daniel-cit**
Fixes #224

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

File: test/integration/simple-example/controls/gcloud.rb [hunk 1]
```diff
@@ -14,6 +14,8 @@
 
 project_id = attribute('project_id')
 blueprint_type = attribute('blueprint_type')
+blueprint_type_semversion = blueprint_type.split('/')[-1]
+SEMVERION_REGEX = /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
```
Comment (morgante) [inline test/integration/simple-example/controls/gcloud.rb:18]:
```suggestion
SEMVERSION_REGEX = /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
```

**Review by morgante — CHANGES_REQUESTED** [review]

File: test/integration/simple-example/controls/gcloud.rb (hunk 1 above)
Comment (daniel-cit) [reply test/integration/simple-example/controls/gcloud.rb]: fixed

**Review by bharathkkb — APPROVED** [review]
